#!/bin/bash


## LOCALDEV settings for django `htmx_project`

## ============================================================================
## standard project-level settings
## ============================================================================

export HTMX__SECRET_KEY="example_secret_key"

export HTMX__DEBUG_JSON="true"

export HTMX__ADMINS_JSON='
    [
      [
        "exampleFirst exampleLast",
        "example@domain.edu"
      ]
    ]
    '

export HTMX__ALLOWED_HOSTS_JSON='["127.0.0.1", "127.0.0.1:8000", "0.0.0.0:8000", "localhost:8000"]'  # must be json

export HTMX__DATABASES_JSON='
    {
      "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "HOST": "",
        "NAME": "../DB/htmx_project.sqlite3",
        "PASSWORD": "",
        "PORT": "",
        "USER": ""
      }
    }
    '

export HTMX__STATIC_URL="/static/"
export HTMX__STATIC_ROOT="/static/"

export HTMX__EMAIL_HOST="localhost"
export HTMX__EMAIL_PORT="1026"  # will be converted to int in settings.py
export HTMX__SERVER_EMAIL="donotreply_x-project@domain.edu"

export HTMX__LOG_PATH="../logs/htmx_project.log"
export HTMX__LOG_LEVEL="DEBUG"

export HTMX__CSRF_TRUSTED_ORIGINS_JSON='["localhost", "127.0.0.1"]'

## https://docs.djangoproject.com/en/3.2/topics/cache/
## - TIMEOUT is in seconds (0 means don't cache); CULL_FREQUENCY defaults to one-third
export HTMX__CACHES_JSON='
{
  "default": {
    "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
    "LOCATION": "../cache_dir",
    "TIMEOUT": 0,
    "OPTIONS": {
        "MAX_ENTRIES": 1000
    }
  }
}
'

## ============================================================================
## app
## ============================================================================

export HTMX__README_URL="https://github.com/birkin/django_template_32_project/blob/main/README.md"

## auth -------------------------------------------------------------

export HTMX__SUPER_USERS_JSON='[
]'

export HTMX__STAFF_USERS_JSON='
[
  "eppn@domain.edu"
]'

export HTMX__STAFF_GROUPER_GROUP="the:group"

export HTMX__TEST_META_DCT_JSON='{
  "Shibboleth-eppn": "eppn@brown.edu",
  "Shibboleth-brownNetId": "First_Last",
  "Shibboleth-mail": "first_last@domain.edu",
  "Shibboleth-givenName": "First",
  "Shibboleth-sn": "Last",
  "Shibboleth-isMemberOf": "aa:bb:cc;dd:ee:ff;the:group;gg:hh"
}'

export HTMX__LOGIN_PROBLEM_EMAIL="htmx_project_problems@domain.edu"


## end --------------------------------------------------------------
