"""
Django settings for django_template_42_project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json, logging, os, pprint
from pathlib import Path

log = logging.getLogger(__name__)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
log.debug( f'BASE_DIR, ``{BASE_DIR}``' )
print( f'BASE_DIR, ``{BASE_DIR}``' )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-3ory+ty87_wq8-21ki6d&a+x=z9_$2m(gr4@vxri@@^g7u!*oc'
SECRET_KEY = os.environ[ 'OCRA_LKP__SECRET_KEY' ]

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = json.loads( os.environ['OCRA_LKP__DEBUG_JSON'] )

ADMINS = json.loads( os.environ['OCRA_LKP__ADMINS_JSON'] )

ALLOWED_HOSTS = json.loads( os.environ['OCRA_LKP__ALLOWED_HOSTS_JSON'] )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ocra_lookup_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ '%s/ocra_lookup_app/templates' % BASE_DIR ],
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = json.loads( os.environ['OCRA_LKP__DATABASES_JSON'] )

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': '../DBs/db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'  ## the default
TIME_ZONE = 'America/New_York'

USE_I18N = True

# USE_TZ = True  ## the default
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = os.environ['OCRA_LKP__STATIC_URL']
STATIC_ROOT = os.environ['OCRA_LKP__STATIC_ROOT']  # needed for collectstatic command

# Email
SERVER_EMAIL = os.environ['OCRA_LKP__SERVER_EMAIL']
EMAIL_HOST = os.environ['OCRA_LKP__EMAIL_HOST']
EMAIL_PORT = int( os.environ['OCRA_LKP__EMAIL_PORT'] )


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': "[%(asctime)s] %(levelname)s [%(module)s-%(funcName)s()::%(lineno)d] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'logfile': {
            'level':'DEBUG',
            'class':'logging.FileHandler',  # note: configure server to use system's log-rotate to avoid permissions issues
            'filename': os.environ['OCRA_LKP__LOG_PATH'],
            'formatter': 'standard',
        },
        'console':{
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'ocra_lookup_app': {
            'handlers': ['logfile'],
            'level': os.environ['OCRA_LKP__LOG_LEVEL'],
            'propagate': False
        },
        # 'django.db.backends': {  # re-enable to check sql-queries! <https://docs.djangoproject.com/en/3.2/topics/logging/#django-db-backends>
        #     'handlers': ['logfile'],
        #     'level': os.environ.get(u'BUL_CBP__LOG_LEVEL'),
        #     'propagate': False
        # },
    }
}

# -------------------------------------------------------------------
# app-level settings
# -------------------------------------------------------------------

# PATTERN_LIB_HEADER_URL = os.environ['OCRA_LKP__PATTERN_LIB_HEADER_URL']
# PATTERN_LIB_CACHE_TIMEOUT = int( os.environ['OCRA_LKP__PATTERN_LIB_CACHE_TIMEOUT_IN_HOURS'] )

## scanned-files data ---------------------------
PDF_JSON_PATH = os.environ['OCRA_LKP__PDF_JSON_PATH']

PDF_DATA = {}  # will be auto-populated
with open( PDF_JSON_PATH, encoding='utf-8' ) as f_reader:
    jsn: str = f_reader.read()
    PDF_DATA = json.loads( jsn )
log.debug( f'pdf_data (partial), ``{pprint.pformat(PDF_DATA)[0:1000]}``' )

PDF_OLDER_THAN_DAYS = int( os.environ['OCRA_LKP__PDF_OLDER_THAN_DAYS'] )
PDF_SQL = os.environ['OCRA_LKP__PDF_SQL']

FILES_URL_PATTERN = os.environ['OCRA_LKP__FILES_URL_PATTERN']

TSV_OUTPUT_DIR_PATH = os.environ['OCRA_LKP__TSV_OUTPUT_DIR_PATH']
